config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: :new do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets, except: [:index, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed
        .select(:id, :content, :picture, :user_id, :created_at).micropost_sort
        .paginate page: params[:page], per_page: Settings.feed.per_page
      @user = current_user
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide :title, t(".about") %>
<h1><%= t ".about" %></h1>
<p>
  <%= t ".the" %> <span class="book">
    <%= link_to t(".ror_tutorial"), "http://www.railstutorial.org/book" %>
  </span>
  <%= t ".is_a" %>
  <%= link_to t(".book"), "http://www.railstutorial.org/book" %>
  <%= t ".and" %>
  <%= link_to t(".screencast_series"), "http://screencasts.railstutorial.org/" %>
  <%= t ".teach" %>
  <%= link_to t(".ror"), "http://rubyonrails.org/" %>.
  <%= t ".sample_application" %>.
</p>

app/views/static_pages/contact.html.erb
<% provide :title, t(".contact") %>
<h1><%= t ".contact" %></h1>
<p>
  <%= t ".contact_ror_tutorial" %>
  <%= link_to t("contact_page"), "http://www.railstutorial.org/contact"%>.
</p>

app/views/static_pages/help.html.erb
<% provide :title, t(".help") %>
<h1><%= t ".help" %></h1>
</p>
  <%= t ".get_help" %>
  <span class="book">
    <%= link_to t(".ror_tutorial"), "http://www.railstutorial.org/book" %>
  </span>
  <%= t ".book" %>.
  <%= t ".to_get_help" %>
  <%= link_to t(".ror_help"), "http://www.railstutorial.org/help" %>.
<p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
      <section class="micropost_form">
        <%= render "shared/micropost_form" %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3><%= t ".micropost_feed" %></h3>
      <%= render "shared/feed" %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1><%= t ".greeting" %></h1>

    <h2>
      <%= t ".home_page" %><%= t ".ror_tutorial" %></a>
      <%= t ".sample_application" %>.
    </h2>

    <%= link_to t(".sign_up_now"), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>